server:
  port: ${PORT:8080}

security:
  basic:
    enabled: false

spring:
  jpa:
    hibernate:
      ddl-auto: update
    database: POSTGRESQL
    show-sql: true
  datasource:
    platform: postgres
    url: jdbc:postgresql:///pathlight?cloudSqlInstance=trim-ruler-367314:us-central1:pathlight-instance&socketFactory=com.google.cloud.sql.postgres.SocketFactory&user=postgres&password=f3oihubfo384t
    username: postgres
    password: f3oihubfo384t
    driverClassName: org.postgresql.Driver
    continue-on-error: true
    initialization-mode: always
  cloud:
    gcp:
      sql:
        database-name: pathlight
        instance-connection-name: trim-ruler-367314:us-central1:pathlight-instance